### ISSUE TITLE
Move Validation Logic from Frontend to Backend

### ISSUE THREAD

**Issue by SkySingh04** [pbdsce/pbwebsite#119]
Currently, the validation logic for user input is implemented on the frontend in our Point Blank website, which is built using Next.js and TypeScript. While frontend validation provides a better user experience, it is not sufficient for ensuring data integrity and security.  

This issue involves removing all validation logic from the frontend and implementing it on the backend to enhance security and maintain a single source of truth for validation.  

**Tasks:**  
1. **Frontend (Next.js):**  
   - Identify and remove all validation logic in the frontend code.  
   - Ensure proper error handling and display user-friendly messages based on backend responses.  

2. **Backend:**  
   - Implement robust validation logic for all user input at the API level.  
   - Use appropriate libraries or custom validation functions for comprehensive input checks.  
   - Update API response structure to include detailed validation error messages.  

3. **Integration:**  
   - Test the frontend to ensure it properly handles validation errors returned from the backend.  
   - Update any relevant TypeScript types/interfaces to reflect changes in validation and API responses.  

**Acceptance Criteria:**  
- All validation logic has been removed from the frontend.  
- Validation is performed entirely on the backend.  
- Frontend handles backend validation error responses gracefully.  
- Thorough testing confirms that the system functions as expected after the changes.  

Please ensure all changes comply with existing code standards and follow the project structure.

**Comment by shreyas-omkar** [comment]
On It Bhaiya.

**Comment by SkySingh04** [comment]
Closed in #130
