### ISSUE TITLE
Implement CSRF token for all API endpoints

### ISSUE THREAD

**Issue by SkySingh04** [pbdsce/pbwebsite#124]
To improve the security of the website, all API endpoints must implement **CSRF (Cross-Site Request Forgery) protection**. This will help prevent malicious actors from executing unauthorized actions on behalf of authenticated users by embedding unique CSRF tokens into requests and validating them on the server side.

---

### **Tasks**:
1. **Generate CSRF Tokens**:
   - Use a secure method to generate CSRF tokens (e.g., libraries like `csurf` for Node.js).
   - Ensure the token is tied to the user's session or cookies.

2. **Include CSRF Tokens in Requests**:
   - Embed the CSRF token in all forms (for POST, PUT, DELETE requests).
   - Include the token in HTTP headers (e.g., `X-CSRF-Token`) for API requests from the frontend.

3. **Validate CSRF Tokens on the Server**:
   - Implement middleware to validate the CSRF token for all incoming API requests.
   - Reject requests with invalid or missing CSRF tokens with a 403 error.

---

### **Acceptance Criteria**:
- All API endpoints validate CSRF tokens successfully.
- Unauthorized requests (missing or invalid tokens) are rejected with a 403 status code.
- API documentation is updated with instructions on how to include the CSRF token.

---

### **References**:
- [[OWASP Guide on CSRF](https://owasp.org/www-community/attacks/csrf)](https://owasp.org/www-community/attacks/csrf)
- [CSRF Protection in Express.js with `csurf`](https://expressjs.com/en/resources/middleware/csurf.html)

**Comment by govindup63** [comment]
can i get this assigned?

**Comment by SkySingh04** [comment]
Closing this as CSRF tokens do not provide any extra layer of security over firebase
