### ISSUE TITLE
login page Bug

### ISSUE THREAD

**Issue by Atharvverma1234** [pbdsce/pbwebsite#16]
After opening the login page and then clicking the back button the background of the whole page changes for all pages like landing, events, leads and achievements. @mohit-nagaraj @alfiyafatima09 
I have attached the 3 images in sequence for your reference.
![1](https://github.com/user-attachments/assets/dd4b72b9-e3ac-4f56-b1a9-bfa22bf14777)
![2](https://github.com/user-attachments/assets/461cfb1b-2ffb-43bf-8e05-912f95a93343)
![3](https://github.com/user-attachments/assets/ebcae435-2def-42ad-a556-6c8e2151602b)

**Comment by suvanbanerjee** [comment]
@Atharvverma1234 This issue is most likely with dark theme @mohit-nagaraj force this website to only use dark-theme will probably fix this

**Comment by mohit-nagaraj** [comment]
@suvanbanerjee u have already enabled defaultTheme="dark" in the pull: #13 , idts the issue no longer exists

**Comment by suvanbanerjee** [comment]
![image](https://github.com/user-attachments/assets/f6df19cb-cd53-443e-afb2-1d7f8009192f)

@Akash-Singh04 its not resolved reopen

**Comment by SkySingh04** [comment]
Oh my
