### ISSUE TITLE
Setup SIH Registraion page backend

### ISSUE THREAD

**Issue by SkySingh04** [pbdsce/pbwebsite#3]
The following details must be stored :
To set up a **Smart India Hackathon (SIH) Registration page backend**, you'll need to collect specific details about participants and their teams. Here are some essential form fields to consider:

### 1. **Team Information**
   - **Team Name**: A unique name for the team.
   - **Team Leader Name**: Name of the team leader.
   - **Team Leader Email**: Email address of the team leader.
   - **Team Leader Phone Number**: Contact number of the team leader.
   - **College/Institution Name**: Name of the institution the team represents.
   - **Team Size**: Number of team members (usually 6 members including the leader).

### 2. **Team Members Information (for each member)**
   - **Name**: Full name of the team member.
   - **Email**: Email address.
   - **Phone Number**: Contact number.
   - **Role in Team**: Role within the team (e.g., Developer, Designer, Tester).
   - **College ID/Enrollment Number**: Official college ID or enrollment number.
   - **Course/Department**: Course and department of study.
   - **Year of Study**: Current year of study (e.g., 2nd Year, 3rd Year).
   - **Branch**: Specific branch of study (e.g., Computer Science, Electronics).

### 3. **Project Information**
   - **Project Title**: Title of the project the team will be working on.
   - **Project Abstract**: A brief description of the project idea.
   - **Problem Statement**: The specific problem statement they are addressing (often provided by SIH).
   - **Technology Stack**: Technologies the team plans to use.

**Comment by SkySingh04** [comment]
Assigned to Mohit

**Comment by mohit-nagaraj** [comment]
Added in `POST /api/registration/sih` 
Sample body: 
{
  "team_info":{
    "team_name": "Test1",
    "team_size": "5",
    "college_name": "DSCE",
    "team_leader": {
      "name": "person1",
      "email": "person@email",
      "phone": "123456789"
    }
  },
  "team_members": [
    {
      "name": "member name1",
      "email": "email1",
      "phone": "1234567890",
      "role": "dev",
      "enrollment_id": "1ds22cs129",
      "course": "b.e.",
      "year_of_study": "2nd year",
      "branch": "computer science"
    },
    {
      "name": "member name2",
      "email": "email2",
      "phone": "1234567890",
      "role": "dev",
      "enrollment_id": "1ds22cs134",
      "course": "b.e.",
      "year_of_study": "2nd year",
      "branch": "computer science"
    }
    ],
  "project_information":{
    "title": "some title",
    "abstract": "some abstaract",
    "problem_statement": "actual ps",
    "tech_stack": "list of comma separated values"
  }
}

More info in the pr
