### ISSUE TITLE
Setup SIH Registration Page Frontend

### ISSUE THREAD

**Issue by SkySingh04** [pbdsce/pbwebsite#4]
This Page needs to follow a design similar to /form route. The fields which need to be filled out from UI are :

### 1. **Team Information**
   - **Team Name**: A unique name for the team.
   - **Team Leader Name**: Name of the team leader.
   - **Team Leader Email**: Email address of the team leader.
   - **Team Leader Phone Number**: Contact number of the team leader.
   - **College/Institution Name**: Name of the institution the team represents.
   - **Team Size**: Number of team members (usually 6 members including the leader).

### 2. **Team Members Information (for each member)**
   - **Name**: Full name of the team member.
   - **Email**: Email address.
   - **Phone Number**: Contact number.
   - **Role in Team**: Role within the team (e.g., Developer, Designer, Tester).
   - **College ID/Enrollment Number**: Official college ID or enrollment number.
   - **Course/Department**: Course and department of study.
   - **Year of Study**: Current year of study (e.g., 2nd Year, 3rd Year).
   - **Branch**: Specific branch of study (e.g., Computer Science, Electronics).

### 3. **Project Information**
   - **Project Title**: Title of the project the team will be working on.
   - **Project Abstract**: A brief description of the project idea.
   - **Problem Statement**: The specific problem statement they are addressing (often provided by SIH).
   - **Technology Stack**: Technologies the team plans to use.

**Comment by SkySingh04** [comment]
Assigned to Kamini

**Comment by kamini08** [comment]
I will take this.
