### ISSUE TITLE
Leads Page  : Data Update and Backend Integration

### ISSUE THREAD

**Issue by SkySingh04** [pbdsce/pbwebsite#6]
Update the data of leads with leads categorized as present leads and past leads.

Data to be fetched from firebase backend. If logged in as admin, A form should be available to add a new lead with necessary details

**Comment by SkySingh04** [comment]
Assigned to Yash

**Comment by XploY04** [comment]
I will work on this.

**Comment by SkySingh04** [comment]
@2004yash You still need to connect the page to firebase and fetch data from there instead of storing on frontend

**Comment by XploY04** [comment]
> @2004yash You still need to connect the page to firebase and fetch data from there instead of storing on frontend

Yes, on it.

**Comment by SkySingh04** [comment]
- Add in edit form
- images from firebase storage
- remove line styling
