### ISSUE TITLE
Update Landing Page UI 

### ISSUE THREAD

**Issue by SkySingh04** [pbdsce/pbwebsite#7]
The following Updates should be made to the landing page:

-  Update banners to only show for ongoing events.
-  Preview of Current Leads
- Update Activities to feature all activites
- Update accomplishments

**Comment by SkySingh04** [comment]
Assigned to Atharv
Ayush kindly pick the other issue you were assigned

**Comment by Atharvverma1234** [comment]
i also want to solve this issue bhaiya

**Comment by SkySingh04** [comment]
Go for it @Atharvverma1234
