### ISSUE TITLE
Fix Achievements Page with broken Images and Inconsistent data

### ISSUE THREAD

**Issue by SkySingh04** [pbdsce/pbwebsite#8]
- Add in a form to easily add achievements data and store in firebase
- Fix currently existing data in https://github.com/pbdsce/landing-page/blob/master/src/core.json and add to firebase

**Comment by TusharMohapatra07** [comment]
@Akash-Singh04  I'm gonna work on this

**Comment by TusharMohapatra07** [comment]
#19

**Comment by SkySingh04** [comment]
@TusharMohapatra07 The frontend for the acheivements page also need to be made under this PR
